### ISSUE TITLE
Always show own points on high score table

### ISSUE THREAD

**Issue by cweiske** [videogameboy76/frozenbubbleandroid#26]
When the arcade game ends, the highscore table is shown.
If you did not make it onto it, you cannot see how much points you had.

Please show the points and time on the last row, highlighted and maybe with a line to separate it from the "real" high scores.

![screenshot_2016-01-27-22-13-03](https://cloud.githubusercontent.com/assets/59036/12690538/8f199048-c6e4-11e5-87c5-4dfffb150ee8.png)

**Comment by videogameboy76** [comment]
Added in version 3.16.
