### ISSUE TITLE
All settings enabled by default

### ISSUE THREAD

**Issue by rugk** [videogameboy76/frozenbubbleandroid#29]
All checkboxes are enabled by default, which is IMHO useless as e.g. e colorblind mode is only useful for some users.
Also e.g. I don't know what the "hurry mode" does.

**Comment by videogameboy76** [comment]
So what is the problem?

"Hurry mode" is where the bubble is automatically launched after a period of inactivity.  Disabling this means a bubble never launches automatically.

**Comment by rugk** [comment]
Ah okay hurry mode is okay, but "colorblind mode" is usually only useful for colorblind people, is not it?
For other users the bubbles are then just not so nice.
