### ISSUE TITLE
Better quality in tablet mode

### ISSUE THREAD

**Issue by rugk** [videogameboy76/frozenbubbleandroid#30]
Especially on tablets you can see the low resolution of the game. This should be changed if possible.

**Comment by videogameboy76** [comment]
That would have to be addressed by a different developer, who would then have to manage the change in size of all the graphics.

I only address software bugs/add new features.  Graphics are not my concern.

**Comment by rugk** [comment]
All right, but is not this the main FrozenBubble repo? if not, where should I report this?
