### ISSUE TITLE
please add changelog to fdroid

### ISSUE THREAD

**Issue by treakiandroid** [videogameboy76/frozenbubbleandroid#35]
hi,

it would be grate if you could add a link to change log at the fdroid repository so users can see what has been updated before upgrading.

thanks in advance

**Comment by videogameboy76** [comment]
No.  They now pull the changes directly from this repo, afaik.

**Comment by sm4rk0** [comment]
Actually, they don't. [Here's the process how to automate that](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/589).
