### ISSUE TITLE
sound effects only partially work

### ISSUE THREAD

**Issue by rkoe** [videogameboy76/frozenbubbleandroid#46]
The sound-effects only partially work / oftern shutter when used on Cyanogenmod 13; it worked on Cyanogenmod 10.
The level-music seems to work.

A screencast showing the problem can be found at http://78.47.161.57/frozen-bubbles-sound-bug.mp4 (~17MB). (The pictures in the video are partially broken, but that's not the problem -- the Frozen Bubble visuals are fine. But the video shows the sound problem quite well.)

Checked again:

- Cyanogenmod 10: works
- Cyanogenmod 11: works
- Cyanogenmod 13: sound effects shutter (see video above)
- LineageOS 14.1: sound effects shutter (like video above)

**Comment by videogameboy76** [comment]
I do not support Cyanogenmod.
