### ISSUE TITLE
Suspicion of Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [videogameboy76/frozenbubbleandroid#48]
Hi @videogameboy76 

Is it an old version of your game [here](https://play.google.com/store/apps/details?id=com.ter.frozenbubble)?

If this is the case, that means this guys just took your source code, added some ads and put it on the Store...

If this is an old version of your app, you can, as you are the owner of the source code, open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this false app from the Store, if it's your wish ;)

Don't forget to tell Google that the app is licensed under GNU GPL v2 license and this guy is violating it...

**Comment by videogameboy76** [comment]
The app in that link no longer exists.
