### ISSUE TITLE
JNI Error

### ISSUE THREAD

**Issue by longtran84** [videogameboy76/frozenbubbleandroid#51]
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.peculiargames.andmodplug.PlayerThread.ModPlug_Init(int) (tried Java_com_peculiargames_andmodplug_PlayerThread_ModPlug_1Init and Java_com_peculiargames_andmodplug_PlayerThread_ModPlug_1Init__I)

**Comment by videogameboy76** [comment]
Insufficient information to address this issue.  Builds just fine for me.  I am assuming this is because the issue creator is using android studio and has not adapted the makefile properly to use the NDK.
