### ISSUE TITLE
CASH - Please help me to resolve it !

### ISSUE THREAD

**Issue by qathuc208** [videogameboy76/frozenbubbleandroid#53]
05-20 13:48:39.965: E/art(1737): No implementation found for boolean com.peculiargames.andmodplug.PlayerThread.ModPlug_Init(int) (tried Java_com_peculiargames_andmodplug_PlayerThread_ModPlug_1Init and Java_com_peculiargames_andmodplug_PlayerThread_ModPlug_1Init__I)
05-20 13:48:39.965: D/AndroidRuntime(1737): Shutting down VM
05-20 13:48:39.966: E/AndroidRuntime(1737): FATAL EXCEPTION: main
05-20 13:48:39.966: E/AndroidRuntime(1737): Process: org.jfedor.frozenbubble, PID: 1737
05-20 13:48:39.966: E/AndroidRuntime(1737): java.lang.UnsatisfiedLinkError: No implementation found for boolean com.peculiargames.andmodplug.PlayerThread.ModPlug_Init(int) (tried Java_com_peculiargames_andmodplug_PlayerThread_ModPlug_1Init and Java_com_peculiargames_andmodplug_PlayerThread_ModPlug_1Init__I)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at com.peculiargames.andmodplug.PlayerThread.ModPlug_Init(Native Method)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at com.peculiargames.andmodplug.PlayerThread.getAndroidAudioTrack(PlayerThread.java:398)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at com.peculiargames.andmodplug.PlayerThread.<init>(PlayerThread.java:320)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at com.peculiargames.andmodplug.MODResourcePlayer.<init>(MODResourcePlayer.java:103)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at com.efortin.frozenbubble.ModPlayer.newMusicPlayer(ModPlayer.java:118)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at com.efortin.frozenbubble.ModPlayer.<init>(ModPlayer.java:68)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at com.efortin.frozenbubble.HomeScreen.startHomeScreen(HomeScreen.java:1221)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at com.efortin.frozenbubble.HomeScreen.access$15(HomeScreen.java:1196)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at com.efortin.frozenbubble.HomeScreen$30$1.run(HomeScreen.java:1016)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at android.os.Handler.handleCallback(Handler.java:739)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at android.os.Looper.loop(Looper.java:148)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at java.lang.reflect.Method.invoke(Native Method)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-20 13:48:39.966: E/AndroidRuntime(1737): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-20 13:48:39.966: I/OMXClient(1737): Using client-side OMX mux.

**Comment by qathuc208** [comment]
05-20 13:45:38.022: E/WVMExtractor(1692): Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found

**Comment by videogameboy76** [comment]
Looks like you need to install the NDK.
